# Generated by Django 5.2.10 on 2026-03-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_type', models.CharField(choices=[('given', '🤝 Men bergan qarz (haqdorlik)'), ('taken', '💸 Men olgan qarz')], max_length=10, verbose_name='Turi')),
                ('person_name', models.CharField(max_length=150, verbose_name='Shaxs ismi')),
                ('person_phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Valyuta')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="To'langan summa")),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('date', models.DateField(verbose_name='Qarz sanasi')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Qaytarish sanasi')),
                ('status', models.CharField(choices=[('open', '🟡 Ochiq'), ('closed', '✅ Yopiq'), ('partial', '🔵 Qisman qaytarildi')], default='open', max_length=10, verbose_name='Holat')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts_app.account', verbose_name='Hisob raqam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Qarz',
                'verbose_name_plural': 'Qarzlar',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name="To'langan summa")),
                ('date', models.DateField(verbose_name="To'lov sanasi")),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debt')),
            ],
            options={
                'verbose_name': "Qarz to'lovi",
                'verbose_name_plural': "Qarz to'lovlari",
                'ordering': ['-date'],
            },
        ),
    ]
