# Generated by Django 5.2.10 on 2026-03-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debt',
            name='debt_type',
            field=models.CharField(choices=[('given', 'Men bergan qarz (haqdorlik)'), ('taken', 'Men olgan qarz')], max_length=10, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='debt',
            name='status',
            field=models.CharField(choices=[('open', 'Ochiq'), ('closed', 'Yopiq'), ('partial', 'Qisman qaytarildi')], default='open', max_length=10, verbose_name='Holat'),
        ),
    ]
