# Generated by Django 5.2.10 on 2026-03-12 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_family_familymember_and_more'),
        ('debts', '0002_alter_debt_debt_type_alter_debt_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='core.familygroup'),
        ),
    ]
