# Generated by Django 5.2.10 on 2026-03-12 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_account_family'),
        ('core', '0005_familygroup_invite_active'),
        ('debts', '0003_debt_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['user', 'family', 'status'], name='debts_debt_user_id_d94fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['family', 'due_date'], name='debts_debt_family__1bf168_idx'),
        ),
        migrations.AddIndex(
            model_name='debt',
            index=models.Index(fields=['user', 'due_date'], name='debts_debt_user_id_d9d76f_idx'),
        ),
    ]
