# Generated by Django 5.2.10 on 2026-03-12 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_family_members(apps, schema_editor):
    FamilyGroup = apps.get_model('core', 'FamilyGroup')
    FamilyMember = apps.get_model('core', 'FamilyMember')
    through = FamilyGroup.members.through

    for row in through.objects.all():
        family_id = getattr(row, 'familygroup_id', None)
        user_id = getattr(row, 'user_id', None)
        if not family_id or not user_id:
            continue
        group = FamilyGroup.objects.filter(id=family_id).first()
        role = 'father' if group and group.created_by_id == user_id else 'son'
        FamilyMember.objects.get_or_create(
            family_id=family_id,
            user_id=user_id,
            defaults={'role': role},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.familygroup'),
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('father', 'Ota'), ('mother', 'Ona'), ('son', "O'g'il"), ('daughter', 'Qiz')], default='father', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.familygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Oila a'zosi",
                'verbose_name_plural': "Oila a'zolari",
                'unique_together': {('family', 'user')},
            },
        ),
        migrations.RunPython(migrate_family_members, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='familygroup',
            name='members',
        ),
        migrations.AddField(
            model_name='familygroup',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='family_groups', through='core.FamilyMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
