# Generated by Django 5.2.10 on 2026-03-12 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_family_familymember_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyJoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('father', 'Ota'), ('mother', 'Ona'), ('son', "O'g'il"), ('daughter', 'Qiz')], default='son', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='core.familygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Oila qo'shilish so'rovi",
                'verbose_name_plural': "Oila qo'shilish so'rovlari",
                'unique_together': {('family', 'user', 'status')},
            },
        ),
    ]
