# Generated by Django 5.2.10 on 2026-03-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_familyjoinrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='invite_active',
            field=models.BooleanField(default=True),
        ),
    ]
