# Generated by Codex on 2026-03-13
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userprofile_gender'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user', 'family'], name='core_fam_user_fa_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family', 'role'], name='core_fam_family_ro_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user', 'role'], name='core_fam_user_ro_idx'),
        ),
        migrations.AddIndex(
            model_name='familyjoinrequest',
            index=models.Index(fields=['family', 'status'], name='core_famjoin_fa_idx'),
        ),
        migrations.AddIndex(
            model_name='familyjoinrequest',
            index=models.Index(fields=['user', 'status'], name='core_famjoin_us_idx'),
        ),
    ]
