# Generated by Django 5.2.10 on 2026-03-13 16:02

from django.db import migrations, models


def _get_index_names(connection, table_name):
    with connection.cursor() as cursor:
        if connection.vendor == 'sqlite':
            cursor.execute(f"PRAGMA index_list('{table_name}')")
            return {row[1] for row in cursor.fetchall()}
        constraints = connection.introspection.get_constraints(cursor, table_name)
        return {name for name, info in constraints.items() if info.get('index')}


def _fix_family_indexes(apps, schema_editor):
    FamilyJoinRequest = apps.get_model('core', 'FamilyJoinRequest')
    FamilyMember = apps.get_model('core', 'FamilyMember')

    old_fjr = [
        models.Index(fields=['family', 'status'], name='core_famjoin_fa_idx'),
        models.Index(fields=['family', 'status'], name='core_familyjoinrequest_family_status_idx'),
        models.Index(fields=['user', 'status'], name='core_famjoin_us_idx'),
        models.Index(fields=['user', 'status'], name='core_familyjoinrequest_user_status_idx'),
    ]
    old_fm = [
        models.Index(fields=['user', 'family'], name='core_fam_user_fa_idx'),
        models.Index(fields=['family', 'role'], name='core_fam_family_ro_idx'),
        models.Index(fields=['user', 'role'], name='core_fam_user_ro_idx'),
    ]

    new_fjr = [
        models.Index(fields=['family', 'status'], name='core_family_family__4c90e1_idx'),
        models.Index(fields=['user', 'status'], name='core_family_user_id_4154f3_idx'),
    ]
    new_fm = [
        models.Index(fields=['user', 'family'], name='core_family_user_id_f6208a_idx'),
        models.Index(fields=['family', 'role'], name='core_family_family__8d15db_idx'),
        models.Index(fields=['user', 'role'], name='core_family_user_id_7a9c30_idx'),
    ]

    existing_fjr = _get_index_names(schema_editor.connection, 'core_familyjoinrequest')
    existing_fm = _get_index_names(schema_editor.connection, 'core_familymember')

    for idx in old_fjr:
        if idx.name in existing_fjr:
            schema_editor.remove_index(FamilyJoinRequest, idx)

    for idx in old_fm:
        if idx.name in existing_fm:
            schema_editor.remove_index(FamilyMember, idx)

    existing_fjr = _get_index_names(schema_editor.connection, 'core_familyjoinrequest')
    existing_fm = _get_index_names(schema_editor.connection, 'core_familymember')

    for idx in new_fjr:
        if idx.name not in existing_fjr:
            schema_editor.add_index(FamilyJoinRequest, idx)

    for idx in new_fm:
        if idx.name not in existing_fm:
            schema_editor.add_index(FamilyMember, idx)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_transaction_indexes'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(_fix_family_indexes, reverse_code=migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='familyjoinrequest',
                    name='core_famjoin_fa_idx',
                ),
                migrations.RemoveIndex(
                    model_name='familyjoinrequest',
                    name='core_familyjoinrequest_family_status_idx',
                ),
                migrations.RemoveIndex(
                    model_name='familyjoinrequest',
                    name='core_famjoin_us_idx',
                ),
                migrations.RemoveIndex(
                    model_name='familyjoinrequest',
                    name='core_familyjoinrequest_user_status_idx',
                ),
                migrations.RemoveIndex(
                    model_name='familymember',
                    name='core_fam_user_fa_idx',
                ),
                migrations.RemoveIndex(
                    model_name='familymember',
                    name='core_fam_family_ro_idx',
                ),
                migrations.RemoveIndex(
                    model_name='familymember',
                    name='core_fam_user_ro_idx',
                ),
                migrations.AddIndex(
                    model_name='familyjoinrequest',
                    index=models.Index(fields=['family', 'status'], name='core_family_family__4c90e1_idx'),
                ),
                migrations.AddIndex(
                    model_name='familyjoinrequest',
                    index=models.Index(fields=['user', 'status'], name='core_family_user_id_4154f3_idx'),
                ),
                migrations.AddIndex(
                    model_name='familymember',
                    index=models.Index(fields=['user', 'family'], name='core_family_user_id_f6208a_idx'),
                ),
                migrations.AddIndex(
                    model_name='familymember',
                    index=models.Index(fields=['family', 'role'], name='core_family_family__8d15db_idx'),
                ),
                migrations.AddIndex(
                    model_name='familymember',
                    index=models.Index(fields=['user', 'role'], name='core_family_user_id_7a9c30_idx'),
                ),
            ],
        ),
    ]
