# Generated by Django 5.2.10 on 2026-03-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('account_type', models.CharField(choices=[('cash', '💵 Naqd pul'), ('card', '💳 Bank kartasi'), ('bank', '🏦 Bank hisob raqami'), ('savings', "💰 Jamg'arma"), ('investment', '📈 Investitsiya'), ('crypto', '₿ Kripto')], default='card', max_length=20, verbose_name='Turi')),
                ('currency', models.CharField(choices=[('UZS', "O'zbek so'mi"), ('USD', 'Dollar'), ('EUR', 'Yevro'), ('RUB', 'Rubl')], default='UZS', max_length=3, verbose_name='Valyuta')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Joriy balans')),
                ('initial_balance', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="Boshlang'ich balans")),
                ('color', models.CharField(choices=[('#6366f1', 'Indigo'), ('#8b5cf6', 'Violet'), ('#ec4899', 'Pink'), ('#f59e0b', 'Amber'), ('#10b981', 'Emerald'), ('#3b82f6', 'Blue'), ('#ef4444', 'Red'), ('#14b8a6', 'Teal')], default='#6366f1', max_length=7, verbose_name='Rang')),
                ('icon', models.CharField(default='💳', max_length=10, verbose_name='Belgi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('include_in_total', models.BooleanField(default=True, verbose_name="Umumiy hisobga qo'shish")),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hisob raqam',
                'verbose_name_plural': 'Hisob raqamlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
