# Generated by Django 5.2.10 on 2026-03-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Bank kartasi'), ('bank', 'Bank hisob raqami'), ('savings', "Jamg'arma"), ('investment', 'Investitsiya'), ('crypto', 'Kripto')], default='card', max_length=20, verbose_name='Turi'),
        ),
        migrations.AlterField(
            model_name='account',
            name='icon',
            field=models.CharField(default='credit-card', max_length=32, verbose_name='Belgi'),
        ),
    ]
