# Generated by Django 5.2.10 on 2026-03-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_alter_account_account_type_alter_account_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='low_balance_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Past balans limiti'),
        ),
    ]
