# Generated by Django 5.2.10 on 2026-03-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('icon', models.CharField(default='📌', max_length=10, verbose_name='Belgi')),
                ('color', models.CharField(default='#6366f1', max_length=7, verbose_name='Rang')),
                ('category_type', models.CharField(choices=[('expense', 'Xarajat'), ('income', 'Daromad'), ('both', 'Ikkalasi')], default='expense', max_length=10)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('expense', '⬇️ Xarajat'), ('income', '⬆️ Daromad'), ('transfer', '↔️ Transfer')], max_length=10, verbose_name='Turi')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Summa')),
                ('currency', models.CharField(default='UZS', max_length=3, verbose_name='Valyuta')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='Tavsif')),
                ('date', models.DateField(verbose_name='Sana')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=15, verbose_name='Valyuta kursi')),
                ('converted_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Konvertatsiya qilingan summa')),
                ('notes', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts_app.account', verbose_name='Hisob raqam')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.category', verbose_name='Kategoriya')),
                ('to_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_transfers', to='accounts_app.account', verbose_name='Qabul qiluvchi hisob')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tranzaksiya',
                'verbose_name_plural': 'Tranzaksiyalar',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
