# Generated by Django 5.2.10 on 2026-03-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='tag', max_length=32, verbose_name='Belgi'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('expense', 'Xarajat'), ('income', 'Daromad'), ('transfer', 'Transfer')], max_length=10, verbose_name='Turi'),
        ),
    ]
