# Generated by Django 5.2.10 on 2026-03-12 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification_family_familymember_and_more'),
        ('transactions', '0002_alter_category_icon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.familygroup'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.familygroup'),
        ),
    ]
