# Generated by Django 5.2.10 on 2026-03-12 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0004_account_family'),
        ('core', '0005_familygroup_invite_active'),
        ('transactions', '0003_category_family_transaction_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'family', 'date'], name='transaction_user_id_86a750_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['family', 'date'], name='transaction_family__6531ed_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_8af7f1_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'date'], name='transaction_transac_6c78ef_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'date'], name='transaction_categor_720c85_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='transaction_account_4f6194_idx'),
        ),
    ]
