# Generated by Django 5.2.10 on 2026-03-10 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('budget_type', models.CharField(choices=[('expense', 'Xarajat limiti'), ('income', 'Daromad maqsadi')], default='expense', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Rejalashtirilgan summa')),
                ('currency', models.CharField(default='UZS', max_length=3)),
                ('month', models.IntegerField(verbose_name='Oy')),
                ('year', models.IntegerField(verbose_name='Yil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.category', verbose_name='Kategoriya')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Byudjet',
                'verbose_name_plural': 'Byudjetlar',
                'ordering': ['-year', '-month'],
            },
        ),
    ]
