# Generated by Django 5.2.10 on 2026-03-12 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0001_initial'),
        ('core', '0003_notification_family_familymember_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='core.familygroup'),
        ),
    ]
