# Generated by Django 5.2.10 on 2026-03-12 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgets', '0002_budget_family'),
        ('core', '0005_familygroup_invite_active'),
        ('transactions', '0003_category_family_transaction_family'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'family', 'year', 'month'], name='budgets_bud_user_id_d38549_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['family', 'year', 'month'], name='budgets_bud_family__e283da_idx'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['user', 'year', 'month'], name='budgets_bud_user_id_39ca25_idx'),
        ),
    ]
